spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
server:
  port: ${PORT:8080}

http.config:
  readTLL: 30000
  connectTLL: 5000
  maxConnTotal: 400
  maxConnPerRoute: 100